display:
  mach: 3
  unit:
    name: "mph"
    factor: 2.23694
quarkus:
  datasource:
    jdbc:
      url: jdbc:postgresql://free-tier5.gcp-europe-west1.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&sslrootcert=$HOME/.postgresql/root.crt&options=--cluster%3Draw-cougar-781
    username: app